name: Generate Cred Instance
on:
  # Trigger on merging to master.
  push:
    branches:
      - master
  # As well as every 24 hours (at 0:00 UTC).
  schedule:
    - cron: 0 0 * * *

jobs:
  GenerateCredInstance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # Required to make github pages deployment work correctly

      - name: Cache Data # Cache SourceCred Data, invalidating if any of the config changes or the SC version is updated
        uses: actions/cache@v2
        with:
          path: '**/cache'
          key: SC-${{ runner.os }}-${{ hashFiles('**/config.json', '**/sourcecred.json', '**/yarn.lock') }}

      - name: Install Packages üîß
        run: yarn --frozen-lockfile

      - name: Load Data and Compute Cred üßÆ
        run: yarn sourcecred go
        env:
          SOURCECRED_GITHUB_TOKEN: fef76de9ccc80afdf2141d73683ca120753aa5a3
          SOURCECRED_DISCORD_TOKEN: ODAzNTc5MTI2MjcxMTgwODUw.YA_1YQ.qD_LNrlpP2H_hdQVQMvTG87T5i0

      - name: Generate Frontend üèó
        run: |
          yarn sourcecred site
          rm -rf ./site/{output,data,config,sourcecred.json}
          cp -r ./{output,data,config,sourcecred.json} ./site/

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: fef76de9ccc80afdf2141d73683ca120753aa5a3
          BRANCH: gh-pages
          FOLDER: site
